"""первая схема: проекты, серии, прогоны, вердикты, кейсы, расход units

Revision ID: 3459a03e3ba6
Revises: 
Create Date: 2026-09-10 18:22:50.385709
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3459a03e3ba6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Имена ENUM-типов, созданных этой ревизией. Список ведётся руками рядом с
# миграцией, а не выводится из моделей: миграция обязана описывать состояние на
# свой момент, а модели уедут вперёд.
_ENUMS = (
    "user_group",
    "target_mode",
    "project_status",
    "metric",
    "metric_source",
    "run_status",
    "run_item_outcome",
    "verdict_group",
    "case_status",
    "artifact_format",
    "ledger_kind",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('target_mode', sa.Enum('SUBDOMAINS', 'PREFIX', 'EXACT', name='target_mode'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('niche', sa.String(length=120), nullable=False),
    sa.Column('geo', sa.String(length=2), nullable=False),
    sa.Column('service_type', sa.String(length=120), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('publishable', sa.Boolean(), nullable=False),
    sa.Column('work_volume', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'COLLECTING', 'COLLECTED', 'CLASSIFIED', 'CASE_READY', 'FAILED', 'SKIPPED', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'target_mode', 'period_start', name='uq_project_domain_period')
    )
    op.create_index(op.f('ix_projects_domain'), 'projects', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('group', sa.Enum('ENGINEER', 'ADMIN', 'USER', name='user_group'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('metric_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.Enum('ORG_TRAFFIC', 'ORG_COST', 'KW_TOP3', 'KW_TOP4_10', 'KW_TOP11_20', 'KW_TOP21_50', 'KW_TOP51_PLUS', 'REFDOMAINS', 'BACKLINKS', 'DR', 'PAGES', 'SEARCH_VOLUME', name='metric'), nullable=False),
    sa.Column('point_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('LIVE', 'FIXTURE', 'MANUAL', name='metric_source'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'metric', 'point_date', 'source', name='uq_metric_point_identity')
    )
    op.create_index(op.f('ix_metric_points_project_id'), 'metric_points', ['project_id'], unique=False)
    op.create_table('rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_ruleset_version')
    )
    op.create_index(op.f('ix_rulesets_is_active'), 'rulesets', ['is_active'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'PARTIAL', 'FAILED', 'CANCELLED', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projects_total', sa.Integer(), nullable=False),
    sa.Column('projects_ok', sa.Integer(), nullable=False),
    sa.Column('projects_failed', sa.Integer(), nullable=False),
    sa.Column('units_estimated', sa.Integer(), nullable=False),
    sa.Column('units_actual', sa.Integer(), nullable=False),
    sa.Column('params_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_started_by'), 'runs', ['started_by'], unique=False)
    op.create_table('run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('raw_domain', sa.String(length=512), nullable=False),
    sa.Column('outcome', sa.Enum('OK', 'SKIPPED_NO_DATA', 'SKIPPED_INVALID', 'SKIPPED_QUOTA', 'FAILED', name='run_item_outcome'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('units_actual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_items_run_id'), 'run_items', ['run_id'], unique=False)
    op.create_table('units_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('RESERVE', 'SPENT', 'CACHED', name='ledger_kind'), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=253), nullable=False),
    sa.Column('units_estimated', sa.Integer(), nullable=True),
    sa.Column('units_actual', sa.Integer(), nullable=True),
    sa.Column('units_per_row', sa.Integer(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_ledger_run_id'), 'units_ledger', ['run_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Enum('GOOD', 'MEDIUM', 'POOR', 'INSUFFICIENT_DATA', name='verdict_group'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('point_a', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('point_b', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ruleset_id', name='uq_verdict_project_ruleset')
    )
    op.create_index(op.f('ix_verdicts_project_id'), 'verdicts', ['project_id'], unique=False)
    op.create_index(op.f('ix_verdicts_ruleset_id'), 'verdicts', ['ruleset_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('verdict_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('anonymized', sa.Boolean(), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'BUILT', 'PUBLISHED', name='case_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_project_id'), 'cases', ['project_id'], unique=False)
    op.create_table('case_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('fmt', sa.Enum('HTML', 'PDF', 'DOCX', 'PPTX', name='artifact_format'), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_artifacts_case_id'), 'case_artifacts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_artifacts_case_id'), table_name='case_artifacts')
    op.drop_table('case_artifacts')
    op.drop_index(op.f('ix_cases_project_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_verdicts_ruleset_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_project_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_units_ledger_run_id'), table_name='units_ledger')
    op.drop_table('units_ledger')
    op.drop_index(op.f('ix_run_items_run_id'), table_name='run_items')
    op.drop_table('run_items')
    op.drop_index(op.f('ix_runs_started_by'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_rulesets_is_active'), table_name='rulesets')
    op.drop_table('rulesets')
    op.drop_index(op.f('ix_metric_points_project_id'), table_name='metric_points')
    op.drop_table('metric_points')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_domain'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###

    # Дописано руками: autogenerate создаёт ENUM-типы неявно (вместе с колонками),
    # но в downgrade их не удаляет. Из-за этого цикл upgrade → downgrade → upgrade
    # падает на `DuplicateObject`: таблиц нет, а типы остались. Поймано примером A1
    # спеки при первом прогоне — то есть миграция «работала» ровно один раз.
    for enum_name in _ENUMS:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
